//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Position { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Goals { get; set; }
        public Nullable<int> Assists { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Team_Id { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
